# Generated by Django 4.1.2 on 2022-10-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='abcd', upload_to='testimonials/'),
            preserve_default=False,
        ),
    ]
