# Generated by Django 4.1.2 on 2022-10-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
